### ISSUE TITLE
cp-server-jolokia: I am 

### ISSUE THREAD

**Issue by geetakudumula** [freemansoft/cp-server-jolokia#1]
Hello,
I am getting "Bad Gateway Errors" while trying the instructions mentioned below to add the Data Source for InfluxDB in Grafana. Can you please suggest why I am getting Bad Gateway Error?

**Configure Grafana to use InfluxDB as a source**
Create a data source that points at InfluxDB
Url: http://influxdb:8086
Database: telegraf
Leave everything else blank
Click Save and Test------------->**At this step**

![image](https://user-images.githubusercontent.com/89669764/133682659-1575ddcf-c312-441f-9c4e-97bfe92cb46b.png)

Thx.

**Comment by freemansoft** [comment]
Looks like there is a version incompatibility in the latest versions of influxdb and grafana.
I pushed a change locks the version numbers of influxdb and Grafana containers.
Didn't do any additional testing other than to make sure the database connection works.
The Telegraf version is _latest_ . I didn't test to make sure that works.
